#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsProjeDeneme
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GumrukDatabaseDeneme")]
	public partial class GumrukDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKULLANICI(KULLANICI instance);
    partial void UpdateKULLANICI(KULLANICI instance);
    partial void DeleteKULLANICI(KULLANICI instance);
    partial void InsertTASIMALAR(TASIMALAR instance);
    partial void UpdateTASIMALAR(TASIMALAR instance);
    partial void DeleteTASIMALAR(TASIMALAR instance);
    #endregion
		
		public GumrukDataClassesDataContext() : 
				base(global::WindowsProjeDeneme.Properties.Settings.Default.GumrukDatabaseDenemeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GumrukDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GumrukDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GumrukDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GumrukDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KULLANICI> KULLANICIs
		{
			get
			{
				return this.GetTable<KULLANICI>();
			}
		}
		
		public System.Data.Linq.Table<TASIMALAR> TASIMALARs
		{
			get
			{
				return this.GetTable<TASIMALAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KULLANICI")]
	public partial class KULLANICI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TC;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Email;
		
		private string _Kullanıcı_Adi;
		
		private string _Kullanıcı_Sifresi;
		
		private string _Adres;
		
		private System.DateTime _D_Tarihi;
		
		private string _Cinsiyet;
		
		private string _Personel_Turu;
		
		private string _Telefon;
		
		private EntitySet<TASIMALAR> _TASIMALARs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTCChanging(string value);
    partial void OnTCChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnKullanıcı_AdiChanging(string value);
    partial void OnKullanıcı_AdiChanged();
    partial void OnKullanıcı_SifresiChanging(string value);
    partial void OnKullanıcı_SifresiChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnD_TarihiChanging(System.DateTime value);
    partial void OnD_TarihiChanged();
    partial void OnCinsiyetChanging(string value);
    partial void OnCinsiyetChanged();
    partial void OnPersonel_TuruChanging(string value);
    partial void OnPersonel_TuruChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public KULLANICI()
		{
			this._TASIMALARs = new EntitySet<TASIMALAR>(new Action<TASIMALAR>(this.attach_TASIMALARs), new Action<TASIMALAR>(this.detach_TASIMALARs));
			OnCreated();
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TC", DbType = "VarChar(50) NOT NULL", IsPrimaryKey = true)]
		public string TC
		{
			get
			{
				return this._TC;
			}
			set
			{
				if ((this._TC != value))
				{
					this.OnTCChanging(value);
					this.SendPropertyChanging();
					this._TC = value;
					this.SendPropertyChanged("TC");
					this.OnTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kullanıcı_Adi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Kullanıcı_Adi
		{
			get
			{
				return this._Kullanıcı_Adi;
			}
			set
			{
				if ((this._Kullanıcı_Adi != value))
				{
					this.OnKullanıcı_AdiChanging(value);
					this.SendPropertyChanging();
					this._Kullanıcı_Adi = value;
					this.SendPropertyChanged("Kullanıcı_Adi");
					this.OnKullanıcı_AdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kullanıcı_Sifresi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Kullanıcı_Sifresi
		{
			get
			{
				return this._Kullanıcı_Sifresi;
			}
			set
			{
				if ((this._Kullanıcı_Sifresi != value))
				{
					this.OnKullanıcı_SifresiChanging(value);
					this.SendPropertyChanging();
					this._Kullanıcı_Sifresi = value;
					this.SendPropertyChanged("Kullanıcı_Sifresi");
					this.OnKullanıcı_SifresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Tarihi", DbType="Date NOT NULL")]
		public System.DateTime D_Tarihi
		{
			get
			{
				return this._D_Tarihi;
			}
			set
			{
				if ((this._D_Tarihi != value))
				{
					this.OnD_TarihiChanging(value);
					this.SendPropertyChanging();
					this._D_Tarihi = value;
					this.SendPropertyChanged("D_Tarihi");
					this.OnD_TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personel_Turu", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string Personel_Turu
		{
			get
			{
				return this._Personel_Turu;
			}
			set
			{
				if ((this._Personel_Turu != value))
				{
					this.OnPersonel_TuruChanging(value);
					this.SendPropertyChanging();
					this._Personel_Turu = value;
					this.SendPropertyChanged("Personel_Turu");
					this.OnPersonel_TuruChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Telefon", DbType = "VarChar(50) NOT NULL")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KULLANICI_TASIMALAR", Storage="_TASIMALARs", ThisKey="TC", OtherKey="Memur_TC")]
		public EntitySet<TASIMALAR> TASIMALARs
		{
			get
			{
				return this._TASIMALARs;
			}
			set
			{
				this._TASIMALARs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TASIMALARs(TASIMALAR entity)
		{
			this.SendPropertyChanging();
			entity.KULLANICI = this;
		}
		
		private void detach_TASIMALARs(TASIMALAR entity)
		{
			this.SendPropertyChanging();
			entity.KULLANICI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TASIMALAR")]
	public partial class TASIMALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Sıra_No;
		
		private string _Plaka;
		
		private string _Arac_Cinsi;
		
		private string _Ulkesi;
		
		private string _Firma;
		
		private int _Surucu_Pasaport_No;
		
		private string _Surucu_Ad;
		
		private string _Surucu_Soyad;
		
		private string _Surucu_Uyruk;
		
		private string _Yuk_Cinsi;
		
		private double _Miktar;
		
		private string _Olcu_Birimi;
		
		private System.DateTime _Giris_Zamanı;
		
		private System.Nullable<System.DateTime> _Cıkıs_Zamanı;
		
		private string _Geldigi_Yer;
		
		private string _Gidecegi_Yer;
		
		private bool _Giris_Cıkıs;
		
		private string _Memur_TC;
		
		private EntityRef<KULLANICI> _KULLANICI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSıra_NoChanging(int value);
    partial void OnSıra_NoChanged();
    partial void OnPlakaChanging(string value);
    partial void OnPlakaChanged();
    partial void OnArac_CinsiChanging(string value);
    partial void OnArac_CinsiChanged();
    partial void OnUlkesiChanging(string value);
    partial void OnUlkesiChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnSurucu_Pasaport_NoChanging(int value);
    partial void OnSurucu_Pasaport_NoChanged();
    partial void OnSurucu_AdChanging(string value);
    partial void OnSurucu_AdChanged();
    partial void OnSurucu_SoyadChanging(string value);
    partial void OnSurucu_SoyadChanged();
    partial void OnSurucu_UyrukChanging(string value);
    partial void OnSurucu_UyrukChanged();
    partial void OnYuk_CinsiChanging(string value);
    partial void OnYuk_CinsiChanged();
    partial void OnMiktarChanging(double value);
    partial void OnMiktarChanged();
    partial void OnOlcu_BirimiChanging(string value);
    partial void OnOlcu_BirimiChanged();
    partial void OnGiris_ZamanıChanging(System.DateTime value);
    partial void OnGiris_ZamanıChanged();
    partial void OnCıkıs_ZamanıChanging(System.Nullable<System.DateTime> value);
    partial void OnCıkıs_ZamanıChanged();
    partial void OnGeldigi_YerChanging(string value);
    partial void OnGeldigi_YerChanged();
    partial void OnGidecegi_YerChanging(string value);
    partial void OnGidecegi_YerChanged();
    partial void OnGiris_CıkısChanging(bool value);
    partial void OnGiris_CıkısChanged();
    partial void OnMemur_TCChanging(string value);
    partial void OnMemur_TCChanged();
    #endregion
		
		public TASIMALAR()
		{
			this._KULLANICI = default(EntityRef<KULLANICI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sıra_No", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Sıra_No
		{
			get
			{
				return this._Sıra_No;
			}
			set
			{
				if ((this._Sıra_No != value))
				{
					this.OnSıra_NoChanging(value);
					this.SendPropertyChanging();
					this._Sıra_No = value;
					this.SendPropertyChanged("Sıra_No");
					this.OnSıra_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plaka", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Plaka
		{
			get
			{
				return this._Plaka;
			}
			set
			{
				if ((this._Plaka != value))
				{
					this.OnPlakaChanging(value);
					this.SendPropertyChanging();
					this._Plaka = value;
					this.SendPropertyChanged("Plaka");
					this.OnPlakaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arac_Cinsi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Arac_Cinsi
		{
			get
			{
				return this._Arac_Cinsi;
			}
			set
			{
				if ((this._Arac_Cinsi != value))
				{
					this.OnArac_CinsiChanging(value);
					this.SendPropertyChanging();
					this._Arac_Cinsi = value;
					this.SendPropertyChanged("Arac_Cinsi");
					this.OnArac_CinsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulkesi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ulkesi
		{
			get
			{
				return this._Ulkesi;
			}
			set
			{
				if ((this._Ulkesi != value))
				{
					this.OnUlkesiChanging(value);
					this.SendPropertyChanging();
					this._Ulkesi = value;
					this.SendPropertyChanged("Ulkesi");
					this.OnUlkesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surucu_Pasaport_No", DbType="Int NOT NULL")]
		public int Surucu_Pasaport_No
		{
			get
			{
				return this._Surucu_Pasaport_No;
			}
			set
			{
				if ((this._Surucu_Pasaport_No != value))
				{
					this.OnSurucu_Pasaport_NoChanging(value);
					this.SendPropertyChanging();
					this._Surucu_Pasaport_No = value;
					this.SendPropertyChanged("Surucu_Pasaport_No");
					this.OnSurucu_Pasaport_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surucu_Ad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surucu_Ad
		{
			get
			{
				return this._Surucu_Ad;
			}
			set
			{
				if ((this._Surucu_Ad != value))
				{
					this.OnSurucu_AdChanging(value);
					this.SendPropertyChanging();
					this._Surucu_Ad = value;
					this.SendPropertyChanged("Surucu_Ad");
					this.OnSurucu_AdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surucu_Soyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surucu_Soyad
		{
			get
			{
				return this._Surucu_Soyad;
			}
			set
			{
				if ((this._Surucu_Soyad != value))
				{
					this.OnSurucu_SoyadChanging(value);
					this.SendPropertyChanging();
					this._Surucu_Soyad = value;
					this.SendPropertyChanged("Surucu_Soyad");
					this.OnSurucu_SoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surucu_Uyruk", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surucu_Uyruk
		{
			get
			{
				return this._Surucu_Uyruk;
			}
			set
			{
				if ((this._Surucu_Uyruk != value))
				{
					this.OnSurucu_UyrukChanging(value);
					this.SendPropertyChanging();
					this._Surucu_Uyruk = value;
					this.SendPropertyChanged("Surucu_Uyruk");
					this.OnSurucu_UyrukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yuk_Cinsi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Yuk_Cinsi
		{
			get
			{
				return this._Yuk_Cinsi;
			}
			set
			{
				if ((this._Yuk_Cinsi != value))
				{
					this.OnYuk_CinsiChanging(value);
					this.SendPropertyChanging();
					this._Yuk_Cinsi = value;
					this.SendPropertyChanged("Yuk_Cinsi");
					this.OnYuk_CinsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miktar", DbType="Float NOT NULL")]
		public double Miktar
		{
			get
			{
				return this._Miktar;
			}
			set
			{
				if ((this._Miktar != value))
				{
					this.OnMiktarChanging(value);
					this.SendPropertyChanging();
					this._Miktar = value;
					this.SendPropertyChanged("Miktar");
					this.OnMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Olcu_Birimi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Olcu_Birimi
		{
			get
			{
				return this._Olcu_Birimi;
			}
			set
			{
				if ((this._Olcu_Birimi != value))
				{
					this.OnOlcu_BirimiChanging(value);
					this.SendPropertyChanging();
					this._Olcu_Birimi = value;
					this.SendPropertyChanged("Olcu_Birimi");
					this.OnOlcu_BirimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giris_Zamanı", DbType="DateTime NOT NULL")]
		public System.DateTime Giris_Zamanı
		{
			get
			{
				return this._Giris_Zamanı;
			}
			set
			{
				if ((this._Giris_Zamanı != value))
				{
					this.OnGiris_ZamanıChanging(value);
					this.SendPropertyChanging();
					this._Giris_Zamanı = value;
					this.SendPropertyChanged("Giris_Zamanı");
					this.OnGiris_ZamanıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cıkıs_Zamanı", DbType="DateTime")]
		public System.Nullable<System.DateTime> Cıkıs_Zamanı
		{
			get
			{
				return this._Cıkıs_Zamanı;
			}
			set
			{
				if ((this._Cıkıs_Zamanı != value))
				{
					this.OnCıkıs_ZamanıChanging(value);
					this.SendPropertyChanging();
					this._Cıkıs_Zamanı = value;
					this.SendPropertyChanged("Cıkıs_Zamanı");
					this.OnCıkıs_ZamanıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geldigi_Yer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Geldigi_Yer
		{
			get
			{
				return this._Geldigi_Yer;
			}
			set
			{
				if ((this._Geldigi_Yer != value))
				{
					this.OnGeldigi_YerChanging(value);
					this.SendPropertyChanging();
					this._Geldigi_Yer = value;
					this.SendPropertyChanged("Geldigi_Yer");
					this.OnGeldigi_YerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gidecegi_Yer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Gidecegi_Yer
		{
			get
			{
				return this._Gidecegi_Yer;
			}
			set
			{
				if ((this._Gidecegi_Yer != value))
				{
					this.OnGidecegi_YerChanging(value);
					this.SendPropertyChanging();
					this._Gidecegi_Yer = value;
					this.SendPropertyChanged("Gidecegi_Yer");
					this.OnGidecegi_YerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Giris/Cıkıs]", Storage="_Giris_Cıkıs", DbType="Bit NOT NULL")]
		public bool Giris_Cıkıs
		{
			get
			{
				return this._Giris_Cıkıs;
			}
			set
			{
				if ((this._Giris_Cıkıs != value))
				{
					this.OnGiris_CıkısChanging(value);
					this.SendPropertyChanging();
					this._Giris_Cıkıs = value;
					this.SendPropertyChanged("Giris_Cıkıs");
					this.OnGiris_CıkısChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Memur_TC", DbType = "VarChar(50) NOT NULL")]
		public string Memur_TC
		{
			get
			{
				return this._Memur_TC;
			}
			set
			{
				if ((this._Memur_TC != value))
				{
					if (this._KULLANICI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMemur_TCChanging(value);
					this.SendPropertyChanging();
					this._Memur_TC = value;
					this.SendPropertyChanged("Memur_TC");
					this.OnMemur_TCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KULLANICI_TASIMALAR", Storage="_KULLANICI", ThisKey="Memur_TC", OtherKey="TC", IsForeignKey=true)]
		public KULLANICI KULLANICI
		{
			get
			{
				return this._KULLANICI.Entity;
			}
			set
			{
				KULLANICI previousValue = this._KULLANICI.Entity;
				if (((previousValue != value) 
							|| (this._KULLANICI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KULLANICI.Entity = null;
						previousValue.TASIMALARs.Remove(this);
					}
					this._KULLANICI.Entity = value;
					if ((value != null))
					{
						value.TASIMALARs.Add(this);
						this._Memur_TC = value.TC;
					}
					else
					{
						this._Memur_TC = default(string);
					}
					this.SendPropertyChanged("KULLANICI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
